[package]
name = "malloc-call-core-mac"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk = "3.1.0"
quote = "1.0.9"
proc-macro2 = "1.0"
syn = "1.0.57"

[lib]
proc-macro = true
